### PR TITLE
Fixed bug with travel time wasn't showing properly

### PR DESCRIPTION
**Pull request by Omarrasheed**

### CODE REVIEW

**Review by kevinchan159 — APPROVED** [review]
speedy

**Comment by mattbarker016** [comment]
What was the bug here?

**Comment by Omarrasheed** [comment]
Old behavior: Was displaying the end time incorrectly in the routeOptionsView. It was doing some extra filtering on the returned routes and but it was not grabbing it correctly when there was a walking at the very end.

**Review by ywsang — APPROVED** [review]
lgtm

**Review by mattbarker016 — APPROVED** [review]

**Pull request merged**
