### PR TITLE
Change logic to hide routes with only walking directions

### PR DESCRIPTION
**Pull request by ywsang**
Addresses #219

### CODE REVIEW

**Review by Omarrasheed — APPROVED** [review]
lgtm

**Review by mattbarker016 — COMMENTED** [review]
Hard to know whether this works from these changes, going to assume this works based on how the app is structured elsewhere. Nice spacing fix too!

**Comment by ywsang** [comment]
> Hard to know whether this works from these changes, going to assume this works based on how the app is structured elsewhere. Nice spacing fix too!

It seemed to work when I tested on device with different combinations of favorite destinations!

**Comment by mattbarker016** [comment]
Good to know, cool beans!

**Pull request merged**
